// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwoGirls.DataLayer.Context;

#nullable disable

namespace TwoGirls.DataLayer.Migrations
{
    [DbContext(typeof(TwogirsContext))]
    partial class TwogirsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClose")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClose = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CartId = 1,
                            ProductId = 3,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            Name = "Men's"
                        },
                        new
                        {
                            Id = 2,
                            IsDelete = false,
                            Name = "Women's"
                        },
                        new
                        {
                            Id = 3,
                            IsDelete = false,
                            Name = "Featured Categories"
                        },
                        new
                        {
                            Id = 4,
                            IsDelete = false,
                            Name = "New Collection",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsDelete = false,
                            Name = "Most Visited",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsDelete = false,
                            Name = "Best Sellers",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsDelete = false,
                            Name = "Discounted",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            IsDelete = false,
                            Name = "New Collection",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsDelete = false,
                            Name = "Most Visited",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            IsDelete = false,
                            Name = "Best Sellers",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsDelete = false,
                            Name = "Discounted",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 12,
                            IsDelete = false,
                            Name = "Fashion and Trends",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 13,
                            IsDelete = false,
                            Name = "Designer Outlet",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 14,
                            IsDelete = false,
                            Name = "Sports Glasses",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsDelete = false,
                            Name = "Glasses for Couples",
                            ParentId = 3
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CategoryToProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryToProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 12,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 12
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.DiscountCode", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UseableCount")
                        .HasColumnType("int");

                    b.HasKey("DiscountId");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.ImagePath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ImagePaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "v1.webp",
                            ProductId = 1,
                            Url = "/image/sunglasses/v1.webp"
                        },
                        new
                        {
                            Id = 2,
                            Name = "v2.webp",
                            ProductId = 1,
                            Url = "/image/sunglasses/v2.webp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "a1.webp",
                            ProductId = 2,
                            Url = "/image/sunglasses/a1.webp"
                        },
                        new
                        {
                            Id = 4,
                            Name = "a2.webp",
                            ProductId = 2,
                            Url = "/image/sunglasses/a2.webp"
                        },
                        new
                        {
                            Id = 5,
                            Name = "b1.webp",
                            ProductId = 3,
                            Url = "/image/sunglasses/b1.webp"
                        },
                        new
                        {
                            Id = 6,
                            Name = "b2.webp",
                            ProductId = 3,
                            Url = "/image/sunglasses/b2.webp"
                        },
                        new
                        {
                            Id = 7,
                            Name = "c1.webp",
                            ProductId = 4,
                            Url = "/image/sunglasses/c1.webp"
                        },
                        new
                        {
                            Id = 8,
                            Name = "c2.webp",
                            ProductId = 4,
                            Url = "/image/sunglasses/c2.webp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "e1.webp",
                            ProductId = 5,
                            Url = "/image/sunglasses/e1.webp"
                        },
                        new
                        {
                            Id = 10,
                            Name = "e2.webp",
                            ProductId = 5,
                            Url = "/image/sunglasses/e2.webp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "f1.webp",
                            ProductId = 6,
                            Url = "/image/sunglasses/f1.webp"
                        },
                        new
                        {
                            Id = 12,
                            Name = "f2.webp",
                            ProductId = 6,
                            Url = "/image/sunglasses/f2.webp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "g1.webp",
                            ProductId = 7,
                            Url = "/image/sunglasses/g1.webp"
                        },
                        new
                        {
                            Id = 14,
                            Name = "g2.webp",
                            ProductId = 7,
                            Url = "/image/sunglasses/g2.webp"
                        },
                        new
                        {
                            Id = 15,
                            Name = "s1.webp",
                            ProductId = 8,
                            Url = "/image/sunglasses/s1.webp"
                        },
                        new
                        {
                            Id = 16,
                            Name = "s2.webp",
                            ProductId = 8,
                            Url = "/image/sunglasses/s2.webp"
                        },
                        new
                        {
                            Id = 17,
                            Name = "h1.webp",
                            ProductId = 9,
                            Url = "/image/sunglasses/h1.webp"
                        },
                        new
                        {
                            Id = 18,
                            Name = "h2.webp",
                            ProductId = 9,
                            Url = "/image/sunglasses/h2.webp"
                        },
                        new
                        {
                            Id = 19,
                            Name = "w1.webp",
                            ProductId = 10,
                            Url = "/image/sunglasses/w1.webp"
                        },
                        new
                        {
                            Id = 20,
                            Name = "w2.webp",
                            ProductId = 10,
                            Url = "/image/sunglasses/w2.webp"
                        },
                        new
                        {
                            Id = 21,
                            Name = "r1.webp",
                            ProductId = 11,
                            Url = "/image/sunglasses/r1.webp"
                        },
                        new
                        {
                            Id = 22,
                            Name = "r2.webp",
                            ProductId = 11,
                            Url = "/image/sunglasses/r2.webp"
                        },
                        new
                        {
                            Id = 23,
                            Name = "q1.webp",
                            ProductId = 12,
                            Url = "/image/sunglasses/q1.webp"
                        },
                        new
                        {
                            Id = 24,
                            Name = "q2.webp",
                            ProductId = 12,
                            Url = "/image/sunglasses/q2.webp"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("CartId1")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinally")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CartId");

                    b.HasIndex("CartId1")
                        .IsUnique()
                        .HasFilter("[CartId1] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Admin Panel"
                        },
                        new
                        {
                            Id = 2,
                            ParentId = 1,
                            Title = "Manage Users"
                        },
                        new
                        {
                            Id = 3,
                            ParentId = 1,
                            Title = "Manage Permissions"
                        },
                        new
                        {
                            Id = 4,
                            ParentId = 1,
                            Title = "Manage Products"
                        },
                        new
                        {
                            Id = 5,
                            ParentId = 1,
                            Title = "Manage Orders"
                        },
                        new
                        {
                            Id = 6,
                            ParentId = 1,
                            Title = "Manage Discounts"
                        },
                        new
                        {
                            Id = 7,
                            ParentId = 1,
                            Title = "Manage Categories"
                        },
                        new
                        {
                            Id = 8,
                            ParentId = 1,
                            Title = "Manage Transactions"
                        },
                        new
                        {
                            Id = 9,
                            ParentId = 2,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 10,
                            ParentId = 2,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 11,
                            ParentId = 2,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 12,
                            ParentId = 2,
                            Title = "Watch Deleted list"
                        },
                        new
                        {
                            Id = 13,
                            ParentId = 3,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 14,
                            ParentId = 3,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 15,
                            ParentId = 3,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 16,
                            ParentId = 3,
                            Title = "Watch Deleted list"
                        },
                        new
                        {
                            Id = 17,
                            ParentId = 4,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 18,
                            ParentId = 4,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 19,
                            ParentId = 4,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 20,
                            ParentId = 4,
                            Title = "Watch Deleted list"
                        },
                        new
                        {
                            Id = 21,
                            ParentId = 5,
                            Title = "Post"
                        },
                        new
                        {
                            Id = 22,
                            ParentId = 5,
                            Title = "Unpost"
                        },
                        new
                        {
                            Id = 23,
                            ParentId = 5,
                            Title = "Watch Posted list"
                        },
                        new
                        {
                            Id = 24,
                            ParentId = 6,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 25,
                            ParentId = 6,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 26,
                            ParentId = 6,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 27,
                            ParentId = 6,
                            Title = "Watch Deleted list"
                        },
                        new
                        {
                            Id = 28,
                            ParentId = 7,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 29,
                            ParentId = 7,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 30,
                            ParentId = 7,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 31,
                            ParentId = 7,
                            Title = "Watch Deleted list"
                        },
                        new
                        {
                            Id = 32,
                            ParentId = 8,
                            Title = "Add or Edit"
                        },
                        new
                        {
                            Id = 33,
                            ParentId = 8,
                            Title = "Delete"
                        },
                        new
                        {
                            Id = 34,
                            ParentId = 8,
                            Title = "Recover"
                        },
                        new
                        {
                            Id = 35,
                            ParentId = 8,
                            Title = "Watch Deleted list"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DiscountedPrice = 1324m,
                            IsDelete = false,
                            ItemNumber = 43555,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9779),
                            PurchasePrice = 1082m,
                            QuantityInStock = 36,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9742),
                            SalesPrice = 1405m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DiscountedPrice = 1328m,
                            IsDelete = false,
                            ItemNumber = 43481,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9812),
                            PurchasePrice = 1077m,
                            QuantityInStock = 41,
                            ReleaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9800),
                            SalesPrice = 1308m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DiscountedPrice = 1287m,
                            IsDelete = false,
                            ItemNumber = 51079,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9841),
                            PurchasePrice = 1356m,
                            QuantityInStock = 12,
                            ReleaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9829),
                            SalesPrice = 1077m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            DiscountedPrice = 1056m,
                            IsDelete = false,
                            ItemNumber = 50868,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9875),
                            PurchasePrice = 1364m,
                            QuantityInStock = 49,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9861),
                            SalesPrice = 1260m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            DiscountedPrice = 1059m,
                            IsDelete = false,
                            ItemNumber = 84937,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9902),
                            PurchasePrice = 1405m,
                            QuantityInStock = 40,
                            ReleaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9890),
                            SalesPrice = 1236m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            DiscountedPrice = 1170m,
                            IsDelete = false,
                            ItemNumber = 39315,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9934),
                            PurchasePrice = 1388m,
                            QuantityInStock = 48,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9918),
                            SalesPrice = 1018m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            DiscountedPrice = 1016m,
                            IsDelete = false,
                            ItemNumber = 85211,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9961),
                            PurchasePrice = 1265m,
                            QuantityInStock = 20,
                            ReleaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9947),
                            SalesPrice = 1234m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            DiscountedPrice = 1280m,
                            IsDelete = false,
                            ItemNumber = 71769,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9990),
                            PurchasePrice = 1315m,
                            QuantityInStock = 42,
                            ReleaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9974),
                            SalesPrice = 1305m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            DiscountedPrice = 1157m,
                            IsDelete = false,
                            ItemNumber = 50838,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(16),
                            PurchasePrice = 1149m,
                            QuantityInStock = 26,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(5),
                            SalesPrice = 1201m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            DiscountedPrice = 1291m,
                            IsDelete = false,
                            ItemNumber = 77878,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(41),
                            PurchasePrice = 1153m,
                            QuantityInStock = 31,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(31),
                            SalesPrice = 1218m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            DiscountedPrice = 1138m,
                            IsDelete = false,
                            ItemNumber = 88003,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(70),
                            PurchasePrice = 1475m,
                            QuantityInStock = 27,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(56),
                            SalesPrice = 1099m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            DiscountedPrice = 1343m,
                            IsDelete = false,
                            ItemNumber = 40370,
                            ProductTypeId = 1,
                            PurchaseDate = new DateTime(2023, 4, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(96),
                            PurchasePrice = 1348m,
                            QuantityInStock = 48,
                            ReleaseDate = new DateTime(2023, 5, 23, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(83),
                            SalesPrice = 1343m,
                            Title = "Reyban Genwux 941"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("productTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Sunglasses"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Eyeglasses"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 5, 28, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(517),
                            ProductId = 1,
                            Rate = 1.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 6, 14, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(538),
                            ProductId = 2,
                            Rate = 2.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 5, 4, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(550),
                            ProductId = 5,
                            Rate = 3.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 6, 3, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(561),
                            ProductId = 6,
                            Rate = 2.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 6, 18, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(573),
                            ProductId = 2,
                            Rate = 5.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            Date = new DateTime(2023, 5, 31, 20, 43, 30, 377, DateTimeKind.Local).AddTicks(583),
                            ProductId = 1,
                            Rate = 3.0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsDelete = false,
                            RoleTitle = "Owner"
                        },
                        new
                        {
                            RoleId = 2,
                            IsDelete = false,
                            RoleTitle = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            IsDelete = false,
                            RoleTitle = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            IsDelete = false,
                            RoleTitle = "User"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 16,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Finaly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Deposit"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Withdraw"
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveCode = "50975f6e0555441db20afedb3fd1e02f",
                            Email = "aqamiladam@gmail.com",
                            FirstName = "Milad",
                            ImagePath = "/image/user-avatar/Milad_profile.jpg",
                            IsActive = true,
                            IsDelete = false,
                            LastName = "Khalatbari",
                            Password = "$HASH$V1$jhUAa6x2XLTQSttEBvsxYw==$Ib1JCvml1e9BLlaqTxYe+ugz3qHe/aig6ks9sNge0lk=",
                            PhoneNumber = "+420730834642",
                            RegisterDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9496),
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActiveCode = "90e2b14b48cc40deafcd275d96c50b94",
                            Email = "samanafra@gmail.com",
                            FirstName = "saman",
                            ImagePath = "/image/user-avatar/saman_profile.jpg",
                            IsActive = true,
                            IsDelete = false,
                            LastName = "afrasiabi",
                            Password = "$HASH$V1$jhUAa6x2XLTQSttEBvsxYw==$Ib1JCvml1e9BLlaqTxYe+ugz3qHe/aig6ks9sNge0lk=",
                            PhoneNumber = "+0985858585",
                            RegisterDate = new DateTime(2023, 6, 23, 20, 43, 30, 376, DateTimeKind.Local).AddTicks(9643),
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.UserDiscountCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiscountCodes");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Address", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Cart", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CartItem", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.Product", "Product")
                        .WithMany("CardItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CategoryToProduct", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Category", "Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.Product", "Product")
                        .WithMany("categoryToProdycts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.CreditCard", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Favorite", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "Users")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.ImagePath", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Product", "Product")
                        .WithMany("ImagePaths")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Order", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.HasOne("TwoGirls.DataLayer.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.Cart", null)
                        .WithOne("Order")
                        .HasForeignKey("TwoGirls.DataLayer.Entities.Order", "CartId1");

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId1");

                    b.Navigation("Address");

                    b.Navigation("Cart");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Permission", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Permission", null)
                        .WithMany("Permissions")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Product", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Review", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.RolePermission", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Transaction", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.User", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.Role", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.UserDiscountCodes", b =>
                {
                    b.HasOne("TwoGirls.DataLayer.Entities.DiscountCode", "DiscountCode")
                        .WithMany("UserDiscountCodes")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoGirls.DataLayer.Entities.User", "User")
                        .WithMany("UserDiscountCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Category", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.DiscountCode", b =>
                {
                    b.Navigation("UserDiscountCodes");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Permission", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Product", b =>
                {
                    b.Navigation("CardItems");

                    b.Navigation("Favorites");

                    b.Navigation("ImagePaths");

                    b.Navigation("Reviews");

                    b.Navigation("categoryToProdycts");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TwoGirls.DataLayer.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cards");

                    b.Navigation("CreditCards");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");

                    b.Navigation("UserDiscountCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
