// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using twoGirlsOnlineShop.Data;

#nullable disable

namespace twoGirlsOnlineShop.Migrations
{
    [DbContext(typeof(TwogirsContext))]
    partial class TwogirsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClose")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClose = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CardItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ProductId");

                    b.ToTable("CardItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CardId = 1,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CardId = 1,
                            ProductId = 3,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Name = "favorite"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Men's"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women's"
                        },
                        new
                        {
                            Id = 3,
                            Name = "New Collection"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Designer Outlet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fashion and Trends"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports Glasses"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Best Sellers"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Most Visited"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fashion and Trends"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Glasses for Couples"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Discounted"
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CategoryToProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryToProducts");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 12,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 12
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CVV2")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("CreditCardNumber")
                        .HasMaxLength(19)
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.ImagePath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ImagePaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "v1.webp",
                            ProductId = 1,
                            Url = "/image/sunglasses/v1.webp"
                        },
                        new
                        {
                            Id = 2,
                            Name = "v2.webp",
                            ProductId = 1,
                            Url = "/image/sunglasses/v2.webp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "a1.webp",
                            ProductId = 2,
                            Url = "/image/sunglasses/a1.webp"
                        },
                        new
                        {
                            Id = 4,
                            Name = "a2.webp",
                            ProductId = 2,
                            Url = "/image/sunglasses/a2.webp"
                        },
                        new
                        {
                            Id = 5,
                            Name = "b1.webp",
                            ProductId = 3,
                            Url = "/image/sunglasses/b1.webp"
                        },
                        new
                        {
                            Id = 6,
                            Name = "b2.webp",
                            ProductId = 3,
                            Url = "/image/sunglasses/b2.webp"
                        },
                        new
                        {
                            Id = 7,
                            Name = "c1.webp",
                            ProductId = 4,
                            Url = "/image/sunglasses/c1.webp"
                        },
                        new
                        {
                            Id = 8,
                            Name = "c2.webp",
                            ProductId = 4,
                            Url = "/image/sunglasses/c2.webp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "e1.webp",
                            ProductId = 5,
                            Url = "/image/sunglasses/e1.webp"
                        },
                        new
                        {
                            Id = 10,
                            Name = "e2.webp",
                            ProductId = 5,
                            Url = "/image/sunglasses/e2.webp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "f1.webp",
                            ProductId = 6,
                            Url = "/image/sunglasses/f1.webp"
                        },
                        new
                        {
                            Id = 12,
                            Name = "f2.webp",
                            ProductId = 6,
                            Url = "/image/sunglasses/f2.webp"
                        },
                        new
                        {
                            Id = 13,
                            Name = "g1.webp",
                            ProductId = 7,
                            Url = "/image/sunglasses/g1.webp"
                        },
                        new
                        {
                            Id = 14,
                            Name = "g2.webp",
                            ProductId = 7,
                            Url = "/image/sunglasses/g2.webp"
                        },
                        new
                        {
                            Id = 15,
                            Name = "s1.webp",
                            ProductId = 8,
                            Url = "/image/sunglasses/s1.webp"
                        },
                        new
                        {
                            Id = 16,
                            Name = "s2.webp",
                            ProductId = 8,
                            Url = "/image/sunglasses/s2.webp"
                        },
                        new
                        {
                            Id = 17,
                            Name = "h1.webp",
                            ProductId = 9,
                            Url = "/image/sunglasses/h1.webp"
                        },
                        new
                        {
                            Id = 18,
                            Name = "h2.webp",
                            ProductId = 9,
                            Url = "/image/sunglasses/h2.webp"
                        },
                        new
                        {
                            Id = 19,
                            Name = "w1.webp",
                            ProductId = 10,
                            Url = "/image/sunglasses/w1.webp"
                        },
                        new
                        {
                            Id = 20,
                            Name = "w2.webp",
                            ProductId = 10,
                            Url = "/image/sunglasses/w2.webp"
                        },
                        new
                        {
                            Id = 21,
                            Name = "r1.webp",
                            ProductId = 11,
                            Url = "/image/sunglasses/r1.webp"
                        },
                        new
                        {
                            Id = 22,
                            Name = "r2.webp",
                            ProductId = 11,
                            Url = "/image/sunglasses/r2.webp"
                        },
                        new
                        {
                            Id = 23,
                            Name = "q1.webp",
                            ProductId = 12,
                            Url = "/image/sunglasses/q1.webp"
                        },
                        new
                        {
                            Id = 24,
                            Name = "q2.webp",
                            ProductId = 12,
                            Url = "/image/sunglasses/q2.webp"
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DiscountedPrice = 1296m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6326),
                            PurchasePrice = 1128m,
                            QuantityInStock = 34,
                            ReleaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6276),
                            SalesPrice = 1036m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DiscountedPrice = 1307m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6335),
                            PurchasePrice = 1409m,
                            QuantityInStock = 39,
                            ReleaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6331),
                            SalesPrice = 1488m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DiscountedPrice = 1341m,
                            PurchaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6341),
                            PurchasePrice = 1176m,
                            QuantityInStock = 29,
                            ReleaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6338),
                            SalesPrice = 1416m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            DiscountedPrice = 1440m,
                            PurchaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6348),
                            PurchasePrice = 1214m,
                            QuantityInStock = 37,
                            ReleaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6344),
                            SalesPrice = 1375m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            DiscountedPrice = 1436m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6355),
                            PurchasePrice = 1144m,
                            QuantityInStock = 29,
                            ReleaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6352),
                            SalesPrice = 1342m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            DiscountedPrice = 1451m,
                            PurchaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6362),
                            PurchasePrice = 1044m,
                            QuantityInStock = 42,
                            ReleaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6358),
                            SalesPrice = 1014m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            DiscountedPrice = 1020m,
                            PurchaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6369),
                            PurchasePrice = 1496m,
                            QuantityInStock = 44,
                            ReleaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6365),
                            SalesPrice = 1090m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            DiscountedPrice = 1459m,
                            PurchaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6376),
                            PurchasePrice = 1438m,
                            QuantityInStock = 46,
                            ReleaseDate = new DateTime(2023, 3, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6373),
                            SalesPrice = 1205m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            DiscountedPrice = 1410m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6383),
                            PurchasePrice = 1015m,
                            QuantityInStock = 17,
                            ReleaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6380),
                            SalesPrice = 1259m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            DiscountedPrice = 1495m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6390),
                            PurchasePrice = 1444m,
                            QuantityInStock = 50,
                            ReleaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6387),
                            SalesPrice = 1119m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            DiscountedPrice = 1153m,
                            PurchaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6397),
                            PurchasePrice = 1006m,
                            QuantityInStock = 20,
                            ReleaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6393),
                            SalesPrice = 1171m,
                            Title = "Reyban Genwux 941"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            DiscountedPrice = 1152m,
                            PurchaseDate = new DateTime(2023, 2, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6403),
                            PurchasePrice = 1120m,
                            QuantityInStock = 12,
                            ReleaseDate = new DateTime(2023, 4, 13, 20, 59, 46, 355, DateTimeKind.Local).AddTicks(6400),
                            SalesPrice = 1122m,
                            Title = "Reyban Genwux 941"
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 1,
                            Rate = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 2,
                            Rate = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 5,
                            Rate = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 6,
                            Rate = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 2,
                            Rate = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "hamamash dagh bood nooshaba dadan porteghal zadan dan dadan !",
                            ProductId = 1,
                            Rate = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfirmPassword = "123",
                            Email = "aqamiladam@gmail.com",
                            FirstName = "Milad",
                            IsAdmin = true,
                            Password = "123",
                            PhoneNumber = "+420730834642",
                            lastName = "Khalatbari"
                        },
                        new
                        {
                            Id = 2,
                            ConfirmPassword = "123",
                            Email = "samanafra@gmail.com",
                            FirstName = "saman",
                            IsAdmin = false,
                            Password = "123",
                            PhoneNumber = "+0985858585",
                            lastName = "afrasiabi"
                        });
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Address", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Card", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CardItem", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.Card", "Card")
                        .WithMany("CardItems")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("twoGirlsOnlineShop.Models.Product", "Product")
                        .WithMany("CardItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CategoryToProduct", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.Category", "Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("twoGirlsOnlineShop.Models.Product", "Product")
                        .WithMany("categoryToProdycts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.CreditCard", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.ImagePath", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.Product", "Product")
                        .WithMany("ImagePaths")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("twoGirlsOnlineShop.Models.User", "User")
                        .WithOne("ImagePath")
                        .HasForeignKey("twoGirlsOnlineShop.Models.ImagePath", "UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Product", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Review", b =>
                {
                    b.HasOne("twoGirlsOnlineShop.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("twoGirlsOnlineShop.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Card", b =>
                {
                    b.Navigation("CardItems");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Category", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.Product", b =>
                {
                    b.Navigation("CardItems");

                    b.Navigation("ImagePaths");

                    b.Navigation("Reviews");

                    b.Navigation("categoryToProdycts");
                });

            modelBuilder.Entity("twoGirlsOnlineShop.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cards");

                    b.Navigation("CreditCards");

                    b.Navigation("Favorites");

                    b.Navigation("ImagePath");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
